app:
  name: "fiber"
  host: "127.0.0.1"
  port: 8000
  url: "http://127.0.0.1:8000"
  version: "0.0.1"
  env: "testing"
  secret: "secret"
  debug: false
  config: "../config"

server:
  prefork: false
  strict: false
  case: false
  etag: false
  bodylimit: 8
  concurrency: 256
  timeout:
    read: 60
    write: 60
    idle: 60
  buffer:
    read: 4
    write: 4

db:
  type: "sqlite"
  host: "127.0.0.1"
  name: "../fiber.testing.sqlite"
  user: "root"
  pass: "root"
  port: 3600
  charset: "utf8mb4"
  collation: "utf8mb4_general_ci"

log:
  server: "../test.log"

file:
  storage: "storage"
  public: "public"
  current: "/Users/kawasakiisao/go/src/github.com/takemo101/go-fiber"

smtp:
  host: "127.0.0.1"
  port: 1025
  identity: ""
  user: ""
  pass: ""
  encryption: ""
  from:
    address: "fiber@xxx.com"
    name: "fiber"

static:
  prefix: "static"
  root: "../static"
  index: "index.html"

template:
  path: "../resource/view"
  suffix: ".html"
  reload: true

cache:
  expiration: 30
  control: false

session:
  expiration: 24
  name: "session"
  domain: ""
  path: "/"
  secure: false
  httponly: false

cors:
  origins: ["*"]
  maxage: 24

jwt:
  signing:
    key: "secret"
    method: "HS256"
  context:
    key: "user"
  lookup: "header:Authorization"
  scheme: "Bearer"
  expiration: 72
